# Generated by Django 4.1 on 2022-10-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('registry', models.CharField(max_length=256)),
                ('ship_class', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('captain', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='boats.officer')),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boats.rank'),
        ),
        migrations.AddField(
            model_name='officer',
            name='ship_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boats.ship'),
        ),
    ]
